services:
  configurator:
    image: frappe/erpnext-worker:${ERPNEXT_VERSION}

  backend:
    image: frappe/erpnext-worker:${ERPNEXT_VERSION}

  frontend:
    image: frappe/erpnext-nginx:${ERPNEXT_VERSION}

  queue-short:
    image: frappe/erpnext-worker:${ERPNEXT_VERSION}

  queue-default:
    image: frappe/erpnext-worker:${ERPNEXT_VERSION}

  queue-long:
    image: frappe/erpnext-worker:${ERPNEXT_VERSION}

  scheduler:
    image: frappe/erpnext-worker:${ERPNEXT_VERSION}
