version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily

  - package-ecosystem: docker
    directory: build/bench
    schedule:
      interval: daily

  - package-ecosystem: docker
    directory: build/nginx
    schedule:
      interval: daily

  - package-ecosystem: docker
    directory: build/worker
    schedule:
      interval: daily

  - package-ecosystem: docker
    directory: build/socketio
    schedule:
      interval: daily

  - package-ecosystem: npm
    directory: build/socketio
    schedule:
      interval: daily
