name: Build Stable

on:
  pull_request:
    branches:
      - main
    paths:
      - build/nginx/**
      - build/socketio/**
      - build/worker/**
      - overrides/**
      - tests/**
      - compose.yaml
      - docker-bake.hcl
      - example.env

  push:
    branches:
      - main
    paths:
      - build/nginx/**
      - build/socketio/**
      - build/worker/**
      - overrides/**
      - tests/**
      - compose.yaml
      - docker-bake.hcl
      - example.env

  # Triggered from frappe/frappe and frappe/erpnext on releases
  repository_dispatch:

  workflow_dispatch:

jobs:
  v12:
    uses: vrslev/frappe_docker/.github/workflows/docker-build-push.yml@beautify
    with:
      repo: erpnext
      version: "13"
      push: ${{ github.repository == 'frappe/frappe_docker' && github.event_name != 'pull_request' }}
    secrets:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}

  v13:
    uses: vrslev/frappe_docker/.github/workflows/docker-build-push.yml@beautify
    with:
      repo: erpnext
      version: "13"
      push: ${{ github.repository == 'frappe/frappe_docker' && github.event_name != 'pull_request' }}
    secrets:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}

  update_example_env:
    runs-on: ubuntu-latest
    if: ${{ github.repository == 'frappe/frappe_docker' && github.event_name != 'pull_request' }}
    needs: v13

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Get latest versions
        run: python3 ./.github/scripts/get_latest_tags.py --repo erpnext --version 13

      - name: Update example.env
        run: python3 ./.github/scripts/update_example_env.py

      - name: Setup Git Credentials
        run: |
          git config --global user.name github-actions
          git config --global user.email github-actions@github.com

      - name: Commit and push
        run: |
          git add example.env
          git commit -m "chore: Update `example.env`"
          git push origin main

  release_helm:
    runs-on: ubuntu-latest
    if: ${{ github.repository == 'frappe/frappe_docker' && github.event_name != 'pull_request' }}
    needs: v13

    steps:
      - name: Setup deploy key
        uses: webfactory/ssh-agent@v0.5.4
        with:
          ssh-private-key: ${{ secrets.HELM_DEPLOY_KEY }}

      - name: Setup Git Credentials
        run: |
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"

      - name: Release
        run: |
          git clone git@github.com:frappe/helm.git && cd helm
          pip install -r release_wizard/requirements.txt
          ./release_wizard/wizard 13 patch --remote origin --ci
