name: Build Develop

on:
  pull_request:
    branches:
      - main
    paths:
      - build/nginx/**
      - build/socketio/**
      - build/worker/**
      - overrides/**
      - tests/**
      - compose.yaml
      - docker-bake.hcl
      - example.env

  schedule:
    # Every day at 12:00 pm
    - cron: 0 0 * * *

  workflow_dispatch:

jobs:
  build_bench:
    name: Bench
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and test
        uses: docker/bake-action@v1.6.0
        with:
          targets: bench-test

      - name: Login
        if: ${{ github.repository == 'frappe/frappe_docker' && github.event_name != 'pull_request' }}
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Push
        if: ${{ github.repository == 'frappe/frappe_docker' && github.event_name != 'pull_request' }}
        uses: docker/bake-action@v1.6.0
        with:
          targets: bench
          push: true

  build_main:
    name: Frappe and ERPNext
    uses: vrslev/frappe_docker/.github/workflows/docker-build-push.yml@beautify
    with:
      repo: erpnext
      version: develop
      push: ${{ github.repository == 'frappe/frappe_docker' && github.event_name != 'pull_request' }}
    secrets:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
