name: Develop build

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Set up environment variable
      env:
        APPS_JSON_BASE64: ${{ secrets.APPS_JSON_BASE64 }}
      run: 
        echo "CUSTOM_VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV
        echo "BUILD_TARGET=custom" >> $GITHUB_ENV
        echo "APPS_JSON_BASE64=${APPS_JSON_BASE64}" >> $GITHUB_ENV

    - name: Docker Build and Push
      uses: ./.github/workflows/docker-build-push.yml
      with:
        repo: erpnext
        version: 14
        push: ${{ github.repository == 'frappe/frappe_docker' && github.event_name != 'pull_request' }}
        # custom_version: ${{ env.CUSTOM_VERSION }}
        # build_target: ${{ env.BUILD_TARGET }}
        # APPS_JSON_BASE64: ${{ env.APPS_JSON_BASE64 }}
