name: Build

on:
  push:
    tags:        
      - 'v*.*.*'           # Push events to every tag not containing /
  workflow_call:
    inputs:
      repo:
        required: true
        type: string
        description: "'erpnext' or 'frappe'"
      version:
        required: true
        type: string
        description: "Major version, git tags should match 'v{version}.*'; or 'develop'"
      push:
        required: true
        type: boolean
    secrets:
      DOCKERHUB_USERNAME:
        required: true
      DOCKERHUB_TOKEN:
        required: true

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    services:
      registry:
        image: registry:2
        ports:
          - 5000:5000

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      # - name: Get tag
      #   run: |
      #     TAG=$(git describe --tags $(git rev-list --tags --max-count=1))
      - name: Branch name
        id: git-meta
        run: |
          echo ::set-output name=SOURCE_NAME::${GITHUB_REF#refs/*/}
          echo ::set-output name=SOURCE_BRANCH::${GITHUB_REF#refs/heads/}
          echo ::set-output name=SOURCE_TAG::${GITHUB_REF#refs/tags/}

      - name: Setup Buildx
        uses: docker/setup-buildx-action@v2
        with:
          driver-opts: network=host

      # - name: Get latest versions
      #   run: python3 ./.github/scripts/get_latest_tags.py --repo ${{ inputs.repo }} --version ${{ inputs.version }}

      - name: Build
        uses: docker/bake-action@v2.3.0
        env:
          APPS_JSON: '[ { "url": "https://github.com/frappe/payments", "branch": "develop" }, { "url": "https://github.com/frappe/erpnext", "branch": "version-14" }, { "url": "https://github.com/frappe/lms", "branch": "main" }, { "url": "https://github.com/frappe/chat", "branch": "main" }, { "url": "https://github.com/yrestom/POS-Awesome", "branch": "version-14" }a, { "url": "https://hieutrluu:${PERSONAL_ACCESS_TOKEN}@github.com/htl-digitalization/tpp_custom", "branch": "main" }, { "url": "https://hieutrluu:${PERSONAL_ACCESS_TOKEN}@github.com/htl-digitalization/tpp_manufacturing", "branch": "main" } ]'
          PERSONAL_ACCESS_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          TAG: ${{ steps.git-meta.outputs.SOURCE_TAG }}
          IMAGE_NAME: tpp-erpnext
          REGISTRY_NAME: hieutrluu
          REGISTRY_USER: localhost:5000/hieutrluu
        with:
          push: true

      # - name: Setup Python
      #   uses: actions/setup-python@v4
      #   with:
      #     python-version: "3.10"

      # - name: Install dependencies
      #   run: |
      #     python -m venv venv
      #     venv/bin/pip install -r requirements-test.txt

      # - name: Test
      #   run: venv/bin/pytest --color=yes

      - name: Login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Push
        uses: docker/bake-action@v2.3.0
        with:
          push: true
