name: Build

on:
  workflow_call:
    inputs:
      version:
        required: true
        type: string
        description: Major Frappe/ERPNext version. 12, 13 or develop.

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      registry:
        image: registry:2
        ports:
          - 5000:5000

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Setup Buildx
        uses: docker/setup-buildx-action@v1
        with:
          driver-opts: network=host

      - name: Install Docker Compose v2
        uses: ndeloof/install-compose-action@4a33bc31f327b8231c4f343f6fba704fedc0fa23

      - name: Get latest versions
        run: ./.github/scripts/get-latest-tags.sh
        env:
          VERSION: ${{ inputs.version }}

      - name: Build
        uses: docker/bake-action@v1.6.0
        with:
          push: true
        env:
          USERNAME: localhost:5000/frappe

      - name: Test
        run: python3 tests/main.py
